[data.datasources.rabbitmq]
name       = "rabbitmq"
driver     = "rabbitmq"
nopassword = true

[data.datasources.rabbitmq.config]
host  = "192.168.2.228"
port  = 5672
vhost = "/"

[data.dataviews.publish_event]
name       = "publish_event"
datasource = "rabbitmq"
query      = "events.test"

[[data.dataviews.publish_event.parameters]]
name     = "payload"
type     = "string"
required = true

[api.views.events]
path      = "events"
method    = "POST"
view_type = "Rest"
auth      = "none"

[api.views.events.handler]
type     = "dataview"
dataview = "publish_event"

[api.views.events.parameter_mapping.body]
payload = "payload"
