[[services]]
name     = "guard"
appId    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee00"
required = true

[[services]]
name     = "sql"
appId    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee01"
required = true

[[services]]
name     = "nosql"
appId    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee02"
required = true

[[services]]
name     = "handlers"
appId    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee03"
required = true

[[services]]
name     = "streams"
appId    = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee04"
required = true

[[datasources]]
name    = "guard-api"
driver  = "http"
service = "guard"

[[datasources]]
name    = "sql-api"
driver  = "http"
service = "sql"

[[datasources]]
name    = "nosql-api"
driver  = "http"
service = "nosql"

[[datasources]]
name    = "handlers-api"
driver  = "http"
service = "handlers"

[[datasources]]
name    = "streams-api"
driver  = "http"
service = "streams"
