[data.datasources.ldap]
name       = "ldap"
driver     = "ldap"
nopassword = true

[data.datasources.ldap.config]
host = "192.168.2.227"
port = 389

[data.dataviews.search_users]
name       = "search_users"
datasource = "ldap"
query      = "dc=rivers,dc=test sub (objectClass=*)"

[data.dataviews.add_user]
name       = "add_user"
datasource = "ldap"
operation  = "add"

[[data.dataviews.add_user.parameters]]
name     = "dn"
type     = "string"
required = true

[[data.dataviews.add_user.parameters]]
name     = "cn"
type     = "string"
required = true

[[data.dataviews.add_user.parameters]]
name     = "sn"
type     = "string"
required = true

[data.dataviews.delete_user]
name       = "delete_user"
datasource = "ldap"
operation  = "delete"

[[data.dataviews.delete_user.parameters]]
name     = "dn"
type     = "string"
required = true

[api.views.users]
path      = "users"
method    = "GET"
view_type = "Rest"
auth      = "none"

[api.views.users.handler]
type     = "dataview"
dataview = "search_users"

[api.views.create_user]
path      = "users"
method    = "POST"
view_type = "Rest"
auth      = "none"

[api.views.create_user.handler]
type     = "dataview"
dataview = "add_user"

[api.views.create_user.parameter_mapping.body]
dn = "dn"
cn = "cn"
sn = "sn"

[api.views.remove_user]
path      = "users/{dn}"
method    = "DELETE"
view_type = "Rest"
auth      = "none"

[api.views.remove_user.handler]
type     = "dataview"
dataview = "delete_user"

[api.views.remove_user.parameter_mapping.path]
dn = "dn"
