bundle_path = "./"

[base]
host      = "0.0.0.0"
port      = 8080
log_level = "info"

[base.logging]
level           = "info"
format          = "json"
app_log_dir     = "log/apps"

[base.tls]
redirect = false

[storage_engine]
backend = "memory"

[engines]
dir = "lib"

[plugins]
dir = "plugins"
