#!/usr/bin/env bash
# package.sh — Build and package a riversd release.
#
# Creates: release/<version>-<timestamp>/{bin,config,log,apphome}/
# Updates: release/latest -> <version>-<timestamp>
# Prunes:  keeps only the 3 most recent releases
#
# Usage: ./scripts/package.sh [--skip-build]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_DIR="${REPO_ROOT}/release"

# ── Version ──────────────────────────────────────────────────────────────────
VERSION=$(grep '^version' "${REPO_ROOT}/Cargo.toml" | head -1 | sed 's/version = "//;s/"//')
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
RELEASE_NAME="${VERSION}-${TIMESTAMP}"
DEST="${RELEASE_DIR}/${RELEASE_NAME}"

# ── Build ─────────────────────────────────────────────────────────────────────
if [[ "${1:-}" != "--skip-build" ]]; then
    echo "→ building binaries (release)..."
    cargo build --release -p riversd -p riversctl -p riverpackage -p rivers-lockbox \
        --manifest-path "${REPO_ROOT}/Cargo.toml"
fi

for bin in riversd riversctl riverpackage rivers-lockbox; do
    if [[ ! -f "${REPO_ROOT}/target/release/${bin}" ]]; then
        echo "error: binary not found: target/release/${bin}" >&2
        exit 1
    fi
done

# ── Create release layout ─────────────────────────────────────────────────────
echo "→ creating ${DEST}/"
mkdir -p "${DEST}/bin"
mkdir -p "${DEST}/config"
mkdir -p "${DEST}/log"
mkdir -p "${DEST}/apphome"

# ── Copy binaries ─────────────────────────────────────────────────────────────
for bin in riversd riversctl riverpackage rivers-lockbox; do
    cp "${REPO_ROOT}/target/release/${bin}" "${DEST}/bin/${bin}"
    echo "   bin/${bin}  ($(du -sh "${DEST}/bin/${bin}" | cut -f1))"
done

# ── Write default config ──────────────────────────────────────────────────────
cat > "${DEST}/config/riversd.toml" << 'EOF'
# riversd.toml — default server configuration
# Generated by scripts/package.sh
#
# bundle_path MUST appear before any [section] header (top-level TOML key).
# Uncomment and set the line below:
#
# bundle_path = "apphome/<your-bundle>/"

[base]
host      = "0.0.0.0"
port      = 8080
log_level = "info"

[base.logging]
# Path is resolved relative to the working directory when riversd starts.
# With the standard release layout (cd release/latest && ./bin/riversd):
local_file_path = "log/riversd.log"

# ── Optional sections (uncomment and fill in as needed) ───────────────────────
# [base.tls]
# cert = "config/cert.pem"
# key  = "config/key.pem"
#
# [lockbox]
# path = "config/keystore.age"
EOF
echo "   config/riversd.toml"

# ── Update latest symlink ─────────────────────────────────────────────────────
ln -sfn "${RELEASE_NAME}" "${RELEASE_DIR}/latest"
echo "   latest -> ${RELEASE_NAME}"

# ── Prune to 3 releases ───────────────────────────────────────────────────────
MAX_RELEASES=3

# Collect versioned dirs sorted oldest-first (exclude dotfiles; works on macOS + Linux)
RELEASES=()
while IFS= read -r name; do
    RELEASES+=("$name")
done < <(
    find "${RELEASE_DIR}" -maxdepth 1 -mindepth 1 -type d \
        ! -name '.*' \
        | xargs -I{} basename {} \
        | sort
)

EXCESS=$(( ${#RELEASES[@]} - MAX_RELEASES ))
if (( EXCESS > 0 )); then
    echo "→ pruning ${EXCESS} old release(s)..."
    for (( i=0; i<EXCESS; i++ )); do
        OLD="${RELEASE_DIR}/${RELEASES[$i]}"
        echo "   removing ${RELEASES[$i]}"
        rm -rf "${OLD}"
    done
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✓ release ready: ${DEST}"
echo ""
echo "  Run:"
echo "    cd ${DEST}"
echo "    # edit config/riversd.toml — set bundle_path = \"apphome/<your-bundle>/\""
echo "    ./bin/riversctl doctor"
echo "    ./bin/riversctl start"
