[data.datasources.nats]
name       = "nats"
driver     = "nats"
nopassword = true

[data.datasources.nats.config]
host = "192.168.2.229"
port = 4222

[data.dataviews.publish_event]
name       = "publish_event"
datasource = "nats"
query      = "events.test"

[[data.dataviews.publish_event.parameters]]
name     = "payload"
type     = "string"
required = true

[api.views.events]
path      = "events"
method    = "POST"
view_type = "Rest"
auth      = "none"

[api.views.events.handler]
type     = "dataview"
dataview = "publish_event"

[api.views.events.parameter_mapping.body]
payload = "payload"
