[[datasources]]
name       = "pg"
driver     = "postgres"
nopassword = true
required   = true

[[datasources]]
name       = "mysql"
driver     = "mysql"
nopassword = true
required   = true

[[datasources]]
name       = "sqlite"
driver     = "sqlite"
nopassword = true
required   = true
