[[datasources]]
name       = "pg"
driver     = "postgres"
lockbox    = "postgres/test"
required   = true

[[datasources]]
name       = "mysql"
driver     = "mysql"
lockbox    = "mysql/test"
required   = true

[[datasources]]
name       = "sqlite"
driver     = "sqlite"
nopassword = true
required   = true
