[[datasources]]
name       = "pg"
driver     = "postgres"
lockbox    = "canary-pg"
required   = true

[[datasources]]
name       = "mysql"
driver     = "mysql"
lockbox    = "canary-mysql"
required   = true

[[datasources]]
name       = "sqlite"
driver     = "sqlite"
nopassword = true
required   = true
