[[datasources]]
name       = "mongo"
driver     = "mongodb"
lockbox    = "mongodb/test"
required   = true

[[datasources]]
name       = "es"
driver     = "elasticsearch"
lockbox    = "elasticsearch/test"
required   = true

[[datasources]]
name       = "couch"
driver     = "couchdb"
lockbox    = "couchdb/test"
required   = true

[[datasources]]
name       = "cassandra"
driver     = "cassandra"
lockbox    = "cassandra/test"
required   = true

[[datasources]]
name       = "ldap"
driver     = "ldap"
lockbox    = "ldap/test"
required   = true

[[datasources]]
name       = "redis"
driver     = "redis"
lockbox    = "redis/test"
required   = true
